servertype: tomcat
virtualname: DataCleaningService
configlist:
- filepath: WEB-INF/classes/jdbc.properties
  params:
    urlAddr: jdbc:mysql://172.17.132.55:3306/epointbid_hfbigdata_3_0?useSSL=true
    username: root
    password: root
    
- filepath: WEB-INF/classes/datacleaning.properties
  params:
    RuleXMLDic: HeFei3.0
    AllowIPs: 0:0:0:0:0:0:0:1;127.0.0.1;172.17.130.43;172.17.130.44;172.17.132.55;172.17.130.43;172.22.205.34
    CleaningJobCron: 
    ThreadCount: 5
    LimitSizeEveryTime: 10000