FROM registry.epoint.com.cn/epoint_base_test/epoint_alpine_tomcat_wkhtmltopdf:v1.12.3
MAINTAINER Shj test <shaojun@epoint.com.cn>
#tomcat
COPY  App  /usr/local/tomcat/webapps/DataCleaningService
ENV appbasepath /usr/local/tomcat 
